name: labcore
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - jupyter_bokeh
  - qcodes
  - bokeh
  - pandas
  - xarray
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - lmfit
  - h5py
  - xhistogram
  - holoviews
  - panel
  - param
  - hvplot
  - versioningit
  - qtpy
  - pip
